find /reacchspace/obj1/netcdf/AGMESH/ -type f -mtime +1 ! -path "./agmesh_scenario_*"
find /reacchspace/obj1/netcdf/AGMESH/pdur/ -type f -mtime +1 ! -name "*.nc"
find /reacchspace/obj1/netcdf/AGMESH/pr/ -type f -mtime +1 ! -name "*.nc"
find /reacchspace/obj1/netcdf/AGMESH/tmmx/ -type f -mtime +1 ! -name "*.nc"
find /reacchspace/obj1/netcdf/AGMESH/tmmn/ -type f -mtime +1 ! -name "*.nc"
find /reacchspace/obj1/netcdf/AGMESH/srad/ -type f -mtime +1 ! -name "*.nc"
find /reacchspace/obj1/netcdf/AGMESH/vs/ -type f -mtime +1 ! -name "*.nc"
find /reacchspace/obj1/netcdf/AGMESH/rmax/ -type f -mtime +1 ! -name "*.nc"
find /reacchspace/obj1/netcdf/AGMESH/rmin/ -type f -mtime +1 ! -name "*.nc"
find /reacchspace/obj1/netcdf/AGMESH/th/ -type f -mtime +1 ! -name "*.nc"
find /reacchspace/obj1/netcdf/AGMESH/sph/ -type f -mtime +1 ! -name "*.nc"

